#!/bin/bash

nginx_config=/etc/nginx/sites-available/ft_server.conf
grep "autoindex on;" $nginx_config > /dev/null

if [ $? -eq 0 ];
then
	echo "Switching autoindex from ON to OFF"
	sed -i 's/autoindex on/autoindex off/g' $nginx_config
else
	echo "Switching autoindex from OFF to ON"
	sed -i 's/autoindex off/autoindex on/g' $nginx_config
fi

service nginx reload
