#!/bin/bash

if  [ $# -eq 1 ] && [[ $1 == "on" || $1 == "off" ]]
then
	sed -i "s/$AUTOINDEX/$1/g" /etc/nginx/conf.d/nginx.template > /etc/nginx/sites-available/ft_server.conf
	service nginx reload
else
	echo "usage: autoindex (on|off)"
fi

